### ISSUE TITLE
Umbilical Cord -  Decide on the connectors needed for elex

### ISSUE THREAD

**Issue by mrgk21** [mrgk21/ROV2019#4]
Related Issues:
#2 
#3

**Comment by mrgk21** [comment]
Connector chosen for power supply:
SP2110/S5 II 1C (This comes with a water sealing cap, @vedangasDARKNINJA )
Datasheet: [Here](http://www.berton-srl.com/Cataloghi/5/Weipu.pdf)
**[In contact with KIRAN electronics, Hyderabad]**

The wire is chosen as 6 mm2 according to the connector specs.

## The problem: 
+ I need 5 6mm2 wires in a single cable for waterproofing purposes. Single core wires can also be used, but they compromise the IP68 part while sealing the connector. **[In contact with ajitesh electricals, kothrud]**

**Comment by mrgk21** [comment]
I am also currently trying to find an **IP68 cat5 Ethernet** connector. 
I am assuming that the total number of Ethernet wires are **2**. 
Please confirm @RasikaShejul

**Comment by RasikaShejul** [comment]
Will confirm soon as camera testing is still in progres.

**Comment by mrgk21** [comment]
3 Ethernet cables is the final count as of 11Jul

**Comment by mrgk21** [comment]
## Meeting review (11Jul)
+ Corrections given in power supply design [Here](https://github.com/mrgk21/ROV2019/issues/2#issuecomment-508906849)
+ Ajit proposed that we buy multiple off-the-shelf power supplies instead of 2 custom ones - economically speaking

**Comment by mrgk21** [comment]
Done with this
